language: cpp

compiler: gcc

install:
  - sudo apt-get install libboost-all-dev

script:
- ./build.sh
- ./build/sandbox hello

after_failure:
- cmake --version
- gcc --version
- g++ --version
- cat ./build.sh
